<?xml version="1.0"?>
<robot name="microbot" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <!-- Import all Gazebo-customization elements, including Gazebo colors --> 
    <xacro:include filename="actual_microbot.gazebo" />

    <!-- Robot Constants -->
    <!-- TODO: damping and friction may limit jitter -->
    <xacro:property name="motor_damping" value="0.00000001" />

    <xacro:property name="motor_friction" value="0.00001" />

    <xacro:property name="platform_height" value="0.0008" />

    <xacro:property name="left_eccenter_position">
        <origin xyz="0 0.022 0.003" rpy="0 0 0" />
    </xacro:property>

    <xacro:property name="right_eccenter_position">
        <origin xyz="0 -0.022 0.003" rpy="0 0 -3.14" />
    </xacro:property>

    <xacro:property name="mesh_mass_center_offset">
        <origin xyz="0 0.0015 -0.001" rpy="0 0 0" />
    </xacro:property>

    <!-- Inertial Macros -->
    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

     <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <!-- Base Link -->
    <link name="base_link">
    </link>

    <joint name="platform_joint" type="fixed">
        <parent link="base_link"></parent>
        <child link="platform_link"></child>
    </joint>

    <!-- Platform link -->
    <link name="platform_link">

        <inertial>
            <mass value="0.100003017"/>
            <inertia ixx="0.000019251"  ixy="0"  ixz="0" iyy="0.000011903" 
                iyz="0" izz="0.000030834" />
        </inertial>

        <!-- <xacro:inertial_cylinder mass="0.1" length="0.0006" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
         -->
        <visual>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/platform visual v2.stl"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/platform collision mesh v7.stl"/>
            </geometry>
            <!-- <surface>
                <bounce restitution_coefficient="0" threshold="0"/>
            </surface> -->
        </collision>
    </link>

    <!-- Left eccenter link -->
    <link name="left_eccenter_link">

        <inertial>
            <xacro:insert_block name="mesh_mass_center_offset" />
            <mass value="0.000208337"/>
            <inertia ixx="2.145e-10"  ixy="0"  ixz="0" iyy="2.666e-10" iyz="0" 
                izz="3.646e-10" />
        </inertial>

        <visual>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/microbot_eccenter_5d.stl"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/microbot_eccenter_5d.stl"/>
            </geometry>
        </collision>

    </link>

    <joint name="platform_to_left_eccenter_joint" type="continuous">
        <xacro:insert_block name="left_eccenter_position" />
        <parent link="platform_link"/>
        <child link="left_eccenter_link"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${motor_damping}" friction="${motor_friction}"/>
    </joint>

    <!-- Right eccenter link -->
    <link name="right_eccenter_link">

        <inertial>
            <xacro:insert_block name="mesh_mass_center_offset" />
            <mass value="0.000208337"/>
            <inertia ixx="2.145e-10"  ixy="0"  ixz="0" iyy="2.666e-10" iyz="0" 
                izz="3.646e-10" />
        </inertial>

        <visual>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/microbot_eccenter_5d.stl"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <mesh scale="0.001 0.001 0.001" 
                    filename="package://microrobot/meshes/microbot_eccenter_5d.stl"/>
            </geometry>
        </collision>

    </link>

    <joint name="platform_to_right_eccenter_joint" type="continuous">
        <xacro:insert_block name="right_eccenter_position" />
        <parent link="platform_link"/>
        <child link="right_eccenter_link"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="${motor_damping}" friction="${motor_friction}"/>
    </joint>

    <!-- IMU link -->
    <link name="imu_link">

        <xacro:inertial_box mass="0.00001" x="0.001" y="0.001" z="0.001">
            <origin xyz="0.0005 0 0.0005" rpy="0 0 0"/>
        </xacro:inertial_box>
        
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </collision>

    </link>

    <joint name="imu_joint" type="fixed">
        <axis xyz="1 0 0"/>      
        <origin xyz="0 0 ${platform_height + 0.0005}"/>
        <parent link="platform_link"/>
        <child link="imu_link"/>
    </joint>

    <!-- AR tag -->
    <link name="ar_tag_link">

        <xacro:inertial_box mass="0.00001" x="0.03" y="0.03" z="0.001">
            <origin xyz="0.0005 0 0.0005" rpy="0 0 0"/>
        </xacro:inertial_box>
        
        <visual>
            <origin rpy="0 0 1.57079633" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://microrobot/ar_tags/ar_tag_0_3cm.dae"/>
            </geometry>
        </visual>
        
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://microrobot/ar_tags/ar_tag_0_3cm.dae"/>
            </geometry>
        </collision>

    </link>

    <joint name="ar_tag_joint" type="fixed">
        <axis xyz="1 0 0"/>      
        <origin xyz="0 0 0.014" rpy="0 0 1.57"/>
        <parent link="base_link"/>
        <child link="ar_tag_link"/>
    </joint>

    <!-- Transmitions -->
    <transmission name="left_motor_transmition">

        <type>transmission_interface/SimpleTransmission</type>
        
        <joint name="platform_to_left_eccenter_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
        </joint>
        
        <actuator name="l_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>

    </transmission>

	<transmission name="right_motor_transmition">
        
        <type>transmission_interface/SimpleTransmission</type>

        <joint name="platform_to_right_eccenter_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
        </joint>
        
        <actuator name="r_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface </hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>

    </transmission>

</robot>