frequency: 100              # Match this to your message publish frequencies!
two_d_mode: true            # 2D NAVIGATION

map_frame: map              # Defaults to "map" if unspecified
odom_frame: odom            # Defaults to "odom" if unspecified
base_link_frame: base_link  # Defaults to "base_link" if unspecified
world_frame: odom           # Defaults to the value of odom_frame if unspecified

imu0: /imu
imu0_config: [false,  false,  false,
              false,  false,  true,
              false,  false, false,
              false, false, true,
              true, false, false]