microbot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  left_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController 
    joint: platform_to_left_eccenter_joint

  right_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController     
    joint: platform_to_right_eccenter_joint

  #TODO: proper pid values may reduce jitter?
  gazebo_ros_control:
    pid_gains:
      platform_to_left_eccenter_joint:
        p: 0.000009

      platform_to_right_eccenter_joint:
        p: 0.000009