microbot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  left_joint_controller:
    type: effort_controllers/JointPositionController 
    joint: platform_to_left_eccenter_joint
    pid: {p: 1, i: 0.01, d: 0.0}

  right_joint_controller:
    type: effort_controllers/JointPositionController      
    joint: platform_to_right_eccenter_joint
    pid: {p: 1, i: 0.01, d: 0.0}